version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/node-app

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: root
    - location: scripts/prepare_app_dir.sh
      timeout: 60
      runas: root
    - location: scripts/fix_permissions.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user