version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum update -y
      - npm install

  build:
    commands:
      - echo Build phase completed

artifacts:
  files:
    - '**/*'